Repository lulutraining/lulutraining, pull requests merged in 2022-12, with the labels that each got.

#7 Style: 캐릭터 리스트 컴포넌트 구현
  components/Icons/Characters/index.tsx
  components/Icons/Characters/style.tsx
  public/images/dorothy.png
  public/images/lion.png
  public/images/scarecrow.png
  public/images/tinman.png
Labels: 🎨 Html & Css

#8 Feat: 비밀번호 표시 아이콘 컴포넌트 생성
  components/Icons/PasswordVisibility/index.tsx
  components/Icons/PasswordVisibility/style.tsx
  components/Icons/index.ts
Labels: ✨ Feature

#9 Feat: 로그인 & 회원가입 Input 컴포넌트 생성
  components/Form/AuthInput/index.tsx
  components/Form/AuthInput/style.tsx
  components/Form/index.ts
  components/index.ts
Labels: ✨ Feature

#10 Feat: 로그인 페이지 UI
  pages/siginin.style.tsx
  styles/signin.tsx
  types/auth.ts
Labels: 🎨 UI

#12 Fix: 파일 위치 수정
  pages/signin.tsx
  styles/siginin.style.tsx
Labels: 🛠 BugFix

#13 Feat: Auth 에러 메세지 컴포넌트 생성
  components/Errors/AuthError/index.tsx
  components/Errors/index.ts
  components/index.ts
Labels: ✨ Feature

#14 Feat: 로그인 기능 구현
  .gitignore
  apis/auth.ts
  package-lock.json
  package.json
  pages/signin.tsx
  services/firebase.ts
  store/atoms.ts
  types/auth.ts
Labels: ✨ Feature

#17 Docs: gitignore package-lock.json 추가
  .gitignore
  package-lock.json
Labels: documentation

#27 Feat: 커스텀 input 컴포넌트 생성
  components/Form/AuthInput/index.tsx
  components/Form/CustomInput/index.tsx
  components/Form/CustomInput/style.tsx
  components/Form/index.ts
  types/auth.ts
Labels: ✨ Feature

#28 Fix: CustomInput value 속성 defaultValue로 수정
  components/Form/CustomInput/index.tsx
Labels: 🛠 BugFix

#33 Fix: firebase env key 변경
  services/firebase.ts
Labels: 🛠 BugFix

#31 Feat: 이전 다음 버튼 컴포넌트 생성
  components/Button/PrevNextButton/index.tsx
  components/Button/PrevNextButton/style.tsx
  components/Button/index.ts
  components/index.ts
Labels: ✨ Feature

#36 Fix: CustomInput 수정 및 로그인페이지 CustomInput 적용
  components/Form/CustomInput/index.tsx
  pages/signin.tsx
Labels: 🛠 BugFix

#34 Feat: 회원가입 페이지 UI
  pages/signup.tsx
  public/images/logo.svg
  styles/emotion.d.ts
  styles/signup.style.tsx
  styles/theme.ts
Labels: 🎨 UI
