Repository lulutraining/lulutraining, pull requests merged in 2023-01, with the labels that each got.

#38 Feat: 회원가입 기능 구현
  apis/auth.ts
  components/Errors/AuthError/index.tsx
  components/Loader/index.tsx
  components/Loader/style.tsx
  components/index.ts
  package.json
  pages/_app.tsx
  pages/signup.tsx
  pages/signup/[check].tsx
  public/images/logo.png
  public/images/logo.svg
  store/atomEffect.ts
  store/atoms.ts
  styles/signup.style.tsx
  types/auth.ts
Labels: ✨ Feature

#39 Feat: 이전버튼 숨김 기능 추가
  components/Button/PrevNextButton/index.tsx
  components/Button/PrevNextButton/style.tsx
Labels: ✨ Feature

#41 Style: customInput 기본 스타일에 border style 추가
  components/Form/CustomInput/style.tsx
  styles/signup.style.tsx
Labels: 🎨 UI

#42 Feat: 회원가입 완료 후 스플래쉬 UI 컴포넌트
  components/Splash/index.tsx
  components/Splash/style.tsx
  components/index.ts
  package.json
  styles/global.tsx
Labels: 🎨 UI

#45 Style: Layout padding 수정
  components/Layout/style.tsx
Labels: 🎨 UI

#48 Feat: 회원가입 버튼 클릭시 회원가입 페이지로 이동
  pages/signin.tsx
Labels: 🛠 BugFix

#46 Feat: 신체정보 기입 , 활동량 체크 하기 전 기입 여부 체크 페이지 UI 구현
  components/Splash/index.tsx
  pages/signup/[check].tsx
  public/images/text-point.png
  styles/signupCheck.style.tsx
Labels: 🎨 UI

#51 Feat: Layout 컴포넌트에 Modal 컴포넌트 추가
  components/Layout/index.tsx
  components/Modal/index.tsx
  components/UnathorizedResult/index.tsx
  components/UnathorizedResult/style.tsx
  components/index.ts
Labels: ✨ Feature

#53 Style: theme color 수정
  styles/emotion.d.ts
  styles/theme.ts
Labels: 🎨 UI

#43 Feat: 활동량 체크 UI 구현
  apis/database.ts
  pages/activecheck.tsx
  services/firebase.ts
  styles/activeCheck.style.tsx
Labels: 🎨 UI

#54 회원가입 페이지 / 모달 컴포넌트 / 체크 페이지 Theme & 로고 수정
  components/Loader/style.tsx
  components/UnathorizedResult/index.tsx
  components/UnathorizedResult/style.tsx
  pages/signup.tsx
  pages/signup/[check].tsx
  public/images/logo.png
  public/images/logo_v2.png
  public/images/symbol.png
  public/images/text-point.png
  styles/global.tsx
  styles/signup.style.tsx
  styles/signupCheck.style.tsx
Labels: 🎨 UI
