Repository lulutraining/lulutraining, pull requests merged in 2023-02, with the labels that each got.

#56 style: 로그인 페이지 GUI3 디자인 수정 반영
  components/Icons/Characters/index.tsx
  components/Icons/Characters/style.tsx
  components/Icons/index.ts
  pages/signin.tsx
  public/images/dorothy.png
  public/images/lion.png
  public/images/scarecrow.png
  public/images/tinman.png
  styles/siginin.style.tsx
Labels: 🎨 UI

#58 Remove: 사용하지 않을 컴포넌트 삭제
  components/Button/PrevNextButton/index.tsx
  components/Button/PrevNextButton/style.tsx
  components/Button/index.ts
  components/Splash/index.tsx
  components/Splash/style.tsx
  components/UnathorizedResult/index.tsx
  components/UnathorizedResult/style.tsx
  components/index.ts
  pages/signup/[check].tsx
Labels: 🔨 Refactor

#60 Feat: 운동량 체크 디자인 변경 및 기능 구현
  components/ActivecheckResult/index.tsx
  components/ActivecheckResult/style.tsx
  components/Layout/style.tsx
  components/Loader/style.tsx
  components/index.ts
  pages/activecheck.tsx
  public/images/activecheck/advenced.png
  public/images/activecheck/basic.png
  public/images/activecheck/intermediate.png
  styles/activeCheck.style.tsx
Labels: ✨ Feature, 🎨 UI

#63 Feat: next.js 서버 로그인/로그아웃 api 구현
  apis/auth.ts
  pages/api/auth/login.ts
  pages/api/auth/logout.ts
  types/auth.ts
Labels: ✨ Feature

#64 Feat: unAuthorizedCheck, removeCookie 유틸 함수 구현
  pages/api/auth/logout.ts
  utils/removeCookie.ts
  utils/unAuthorizedCheck.ts
Labels: ✨ Feature

#65 Feat: firestore database document 읽는 함수 추가
  apis/database.ts
Labels: ✨ Feature

#67 Feat: app 초기 렌더링시 user data 초기값 저장
  pages/_app.tsx
Labels: 🛠 BugFix

#68 Feat: recoil atomEffect localstorage에서 cookie 저장으로 변경
  store/atomEffect.ts
  store/atoms.ts
Labels: ✨ Feature

#69 Feat: 로그인/회원가입 인증로직 적용
  components/Layout/index.tsx
  pages/signin.tsx
  pages/signup.tsx
Labels: ✨ Feature

#70 Fix: 인증관련 함수 제거하고 리턴 함수 바로 실행하도록 수정
  pages/api/auth/login.ts
Labels: 🛠 BugFix

#73 Docs: Readme 내용 수정
  README.md
Labels: 📄 Docs
