Repository lulutraining/lulutraining, pull requests merged in 2023-03, with the labels that each got.

#71 Feat: 개인정보 입력 페이지 구현
  components/Form/CustomInput/index.tsx
  pages/bodycheck.tsx
  styles/bodyCheck.style.tsx
  types/auth.ts
Labels: ✨ Feature

#75 fix: 로그아웃 버튼 가림
  components/Layout/index.tsx
Labels: 🛠 BugFix

#78 Fix: 활동량 체크 페이지 수정
  apis/database.ts
  components/ActivecheckResult/index.tsx
  consts/index.ts
  pages/activecheck.tsx
  public/images/activecheck/advanced.png
  store/atoms.ts
  types/auth.ts
  utils/unAuthorizedCheck.ts
Labels: 🛠 BugFix

#80 feat: 메인페이지 UI 구현
  pages/index.tsx
  styles/home.style.tsx
Labels: 🎨 UI

#79 feat: Thumbnail Component 생성
  components/Thumb/index.tsx
  components/Thumb/style.tsx
  components/index.ts
  pages/index.tsx
  types/training.ts
Labels: ✨ Feature

#84 Fix: 레이아웃 컴포넌트 샘플 로그아웃 버튼 삭제
  components/Layout/index.tsx
Labels: 🛠 BugFix

#85 Fix: 수정된 database.ts 코드에 맞추어 데이터 가져오는 코드 수정
  pages/bodycheck.tsx
Labels: 🛠 BugFix

#86 Feat: mypage header 회원정보수정 기능 추가
  components/Header/index.tsx
Labels: ✨ Feature

#88 Mypage UI 구현
  next.config.js
  package.json
  pages/mypage.tsx
  styles/mypage.style.tsx
  types/training.ts
  utils/unAuthorizedCheck.ts
Labels: 🎨 UI

#89 Feat: contents 페이지 구현
  package.json
  pages/contents/[videoId].tsx
  styles/contents.style.tsx
Labels: ✨ Feature, 🎨 UI
